### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jpaquim** [apinske/virt#4]
Hey!

First of all thanks for the repo, this is a great way to run VMs with the bare minimum scaffolding on macOS.

I wanted to extend it for my use cases, but unfortunately I don't see a license in this repo. Would it be possible for you to add one please @apinske?

Kind regards

**Comment by apinske** [comment]
Thanks for your interest. I'd be pleased to know what you are planning on doing with it.

**Comment by apinske** [comment]
fixed in #5

**Comment by jpaquim** [comment]
Thank you! You can follow along here: https://github.com/pluvial/vm
I'm essentially customizing it to my own use cases, and further documenting the custom Linux/image building process. I really enjoyed the barebones approach you took, compared to others I've seen which are a decent amount more complex.
